#! /bin/bash
#
# Flash an Arduino Mega with STK500v2 using the esp-link built-in programmer
# Basically we first reset the AVR and get in sync, and then send the hex file
#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# Thorsten von Eicken wrote this file. As long as you retain 
# this notice you can do whatever you want with this stuff. If we meet some day, 
# and you think this stuff is worth it, you can buy me a beer in return. 
#
# Danny Backx wrote the changes for Arduino Mega.
# ----------------------------------------------------------------------------

show_help() {
  cat <<EOT
Usage: ${0##*/} [-options...] hostname sketch.hex
Flash the Mega running optiboot attached to esp-link with the sketch.
Note : this is for stk500v2 MCUs, use avrflash for Arduino Uno etc instead.
  -v                    Be verbose
  -h                    show this help

Example: ${0##*/} -v esp-link mysketch.hex
         ${0##*/} 192.168.4.1 mysketch.hex
EOT
}

# ===== Find avrflash

megaflash=$(readlink -e $0)
avrflash=${megaflash%/*}/avrflash
if [ ! -f $avrflash ]; then
  echo "ERROR: Unable to find avrflash" >&2
  exit 1
fi

# ===== Parse arguments

verbose=

while getopts "hv" opt; do
  case "$opt" in
    h) show_help; exit 0 ;;
    v) verbose='-v' ;;
    '?') show_help >&2; exit 1 ;;
  esac
done

# Shift off the options and optional --.
shift "$((OPTIND-1))"

# Get the fixed arguments
if [[ $# != 2 ]]; then
  show_help >&2
  exit 1
fi

# ===== Run avrflash

$avrflash -p atmega2560 $verbose $@
